const data  = [
  {
    id: 1,
    img: "../img/blog-item/blog-item-2.png",
    title:
      "1 Xayotda shunday vaziyatlar bo‘ladiki, kimdan yordam so‘ramang...",
    dec: "Yaqinda bir psixologning suhbatini eshitib qoldim. U aytishicha o‘sha davrda hech qanday moliyaviy muhim qarorlar qabul qilish kerak emas ekan…",
    time: "13.08.2022",
  },
  {
    id: 2,
    img: "../img/blog-item/blog-item-1.png",
    title: "Xayotda shunday vaziyatlar bo‘ladiki, kimdan yordam so‘ramang...",
    dec: "Yaqinda bir psixologning suhbatini eshitib qoldim. U aytishicha o‘sha davrda hech qanday moliyaviy muhim qarorlar qabul qilish kerak emas ekan…",
    time: "13.08.2022",
  },
  {
    id: 3,
    img: "../img/blog-item/blog-item-3.png",
    title: "Xayotda shunday vaziyatlar bo‘ladiki, kimdan yordam so‘ramang...",
    dec: "Yaqinda bir psixologning suhbatini eshitib qoldim. U aytishicha o‘sha davrda hech qanday moliyaviy muhim qarorlar qabul qilish kerak emas ekan…",
    time: "13.08.2022",
  },
  {
    id: 4,
    img: "../img/blog-item/blog-md-item-1.png",
    title: "Xayotda shunday vaziyatlar bo‘ladiki, kimdan yordam so‘ramang...",
    dec: "Yaqinda bir psixologning suhbatini eshitib qoldim. U aytishicha o‘sha davrda hech qanday moliyaviy muhim qarorlar qabul qilish kerak emas ekan…",
    time: "13.08.2022",
  },
  {
    id: 5,
    img: "../img/blog-item/blog-md-item-2.png",
    title: "Xayotda shunday vaziyatlar bo‘ladiki, kimdan yordam so‘ramang...",
    dec: "Yaqinda bir psixologning suhbatini eshitib qoldim. U aytishicha o‘sha davrda hech qanday moliyaviy muhim qarorlar qabul qilish kerak emas ekan…",
    time: "13.08.2022",
  },
  {
    id: 6,
    img: "../img/blog-item/blog-md-item-3.png",
    title: "Xayotda shunday vaziyatlar bo‘ladiki, kimdan yordam so‘ramang...",
    dec: "Yaqinda bir psixologning suhbatini eshitib qoldim. U aytishicha o‘sha davrda hech qanday moliyaviy muhim qarorlar qabul qilish kerak emas ekan…",
    time: "13.08.2022",
  },
  {
    id: 7,
    img: "../img/blog-item/blog-md-item-4.png",
    title: "Xayotda shunday vaziyatlar bo‘ladiki, kimdan yordam so‘ramang...",
    dec: "Yaqinda bir psixologning suhbatini eshitib qoldim. U aytishicha o‘sha davrda hech qanday moliyaviy muhim qarorlar qabul qilish kerak emas ekan…",
    time: "13.08.2022",
  },
  {
    id: 8,
    img: "../img/blog-item/blog-md-item-1.png",
    title:
      "1 Xayotda shunday vaziyatlar bo‘ladiki, kimdan yordam so‘ramang...",
    dec: "Yaqinda bir psixologning suhbatini eshitib qoldim. U aytishicha o‘sha davrda hech qanday moliyaviy muhim qarorlar qabul qilish kerak emas ekan…",
    time: "13.08.2022",
  },
  {
    id: 9,
    img: "../img/blog-item/blog-item-2.png",
    title: "Xayotda shunday vaziyatlar bo‘ladiki, kimdan yordam so‘ramang...",
    dec: "Yaqinda bir psixologning suhbatini eshitib qoldim. U aytishicha o‘sha davrda hech qanday moliyaviy muhim qarorlar qabul qilish kerak emas ekan…",
    time: "13.08.2022",
  },
  {
    id: 10,
    img: "../img/blog-item/blog-item-3.png",
    title: "Xayotda shunday vaziyatlar bo‘ladiki, kimdan yordam so‘ramang...",
    dec: "Yaqinda bir psixologning suhbatini eshitib qoldim. U aytishicha o‘sha davrda hech qanday moliyaviy muhim qarorlar qabul qilish kerak emas ekan…",
    time: "13.08.2022",
  },
  {
    id:11,
    img: "../img/blog-item/blog-item-1.png",
    title: "Xayotda shunday vaziyatlar bo‘ladiki, kimdan yordam so‘ramang...",
    dec: "Yaqinda bir psixologning suhbatini eshitib qoldim. U aytishicha o‘sha davrda hech qanday moliyaviy muhim qarorlar qabul qilish kerak emas ekan…",
    time: "13.08.2022",
  },
  {
    id: 12,
    img: "../img/blog-item/blog-item-3.png",
    title: "Xayotda shunday vaziyatlar bo‘ladiki, kimdan yordam so‘ramang...",
    dec: "Yaqinda bir psixologning suhbatini eshitib qoldim. U aytishicha o‘sha davrda hech qanday moliyaviy muhim qarorlar qabul qilish kerak emas ekan…",
    time: "13.08.2022",
  },
  {
    id: 13,
    img: "../img/blog-item/blog-md-item-1.png",
    title: "Xayotda shunday vaziyatlar bo‘ladiki, kimdan yordam so‘ramang...",
    dec: "Yaqinda bir psixologning suhbatini eshitib qoldim. U aytishicha o‘sha davrda hech qanday moliyaviy muhim qarorlar qabul qilish kerak emas ekan…",
    time: "13.08.2022",
  },
  {
    id: 14,
    img: "../img/blog-item/blog-md-item-2.png",
    title: "Xayotda shunday vaziyatlar bo‘ladiki, kimdan yordam so‘ramang...",
    dec: "Yaqinda bir psixologning suhbatini eshitib qoldim. U aytishicha o‘sha davrda hech qanday moliyaviy muhim qarorlar qabul qilish kerak emas ekan…",
    time: "13.08.2022",
  },
  {
    id: 15,
    img: "../img/blog-item/blog-item-2.png",
    title:
      "1 Xayotda shunday vaziyatlar bo‘ladiki, kimdan yordam so‘ramang...",
    dec: "Yaqinda bir psixologning suhbatini eshitib qoldim. U aytishicha o‘sha davrda hech qanday moliyaviy muhim qarorlar qabul qilish kerak emas ekan…",
    time: "13.08.2022",
  },
  {
    id: 16,
    img: "../img/blog-item/blog-item-1.png",
    title: "Xayotda shunday vaziyatlar bo‘ladiki, kimdan yordam so‘ramang...",
    dec: "Yaqinda bir psixologning suhbatini eshitib qoldim. U aytishicha o‘sha davrda hech qanday moliyaviy muhim qarorlar qabul qilish kerak emas ekan…",
    time: "13.08.2022",
  },
  {
    id: 17,
    img: "../img/blog-item/blog-item-3.png",
    title: "Xayotda shunday vaziyatlar bo‘ladiki, kimdan yordam so‘ramang...",
    dec: "Yaqinda bir psixologning suhbatini eshitib qoldim. U aytishicha o‘sha davrda hech qanday moliyaviy muhim qarorlar qabul qilish kerak emas ekan…",
    time: "13.08.2022",
  },
  {
    id: 18,
    img: "../img/blog-item/blog-md-item-1.png",
    title: "Xayotda shunday vaziyatlar bo‘ladiki, kimdan yordam so‘ramang...",
    dec: "Yaqinda bir psixologning suhbatini eshitib qoldim. U aytishicha o‘sha davrda hech qanday moliyaviy muhim qarorlar qabul qilish kerak emas ekan…",
    time: "13.08.2022",
  },
  {
    id: 19,
    img: "../img/blog-item/blog-md-item-2.png",
    title: "Xayotda shunday vaziyatlar bo‘ladiki, kimdan yordam so‘ramang...",
    dec: "Yaqinda bir psixologning suhbatini eshitib qoldim. U aytishicha o‘sha davrda hech qanday moliyaviy muhim qarorlar qabul qilish kerak emas ekan…",
    time: "13.08.2022",
  },
  {
    id: 20,
    img: "../img/blog-item/blog-md-item-3.png",
    title: "Xayotda shunday vaziyatlar bo‘ladiki, kimdan yordam so‘ramang...",
    dec: "Yaqinda bir psixologning suhbatini eshitib qoldim. U aytishicha o‘sha davrda hech qanday moliyaviy muhim qarorlar qabul qilish kerak emas ekan…",
    time: "13.08.2022",
  },
  {
    id: 21,
    img: "../img/blog-item/blog-md-item-4.png",
    title: "Xayotda shunday vaziyatlar bo‘ladiki, kimdan yordam so‘ramang...",
    dec: "Yaqinda bir psixologning suhbatini eshitib qoldim. U aytishicha o‘sha davrda hech qanday moliyaviy muhim qarorlar qabul qilish kerak emas ekan…",
    time: "13.08.2022",
  },
  {
    id: 22,
    img: "../img/blog-item/blog-md-item-1.png",
    title:
      "1 Xayotda shunday vaziyatlar bo‘ladiki, kimdan yordam so‘ramang...",
    dec: "Yaqinda bir psixologning suhbatini eshitib qoldim. U aytishicha o‘sha davrda hech qanday moliyaviy muhim qarorlar qabul qilish kerak emas ekan…",
    time: "13.08.2022",
  },
  {
    id: 23,
    img: "../img/blog-item/blog-item-2.png",
    title: "Xayotda shunday vaziyatlar bo‘ladiki, kimdan yordam so‘ramang...",
    dec: "Yaqinda bir psixologning suhbatini eshitib qoldim. U aytishicha o‘sha davrda hech qanday moliyaviy muhim qarorlar qabul qilish kerak emas ekan…",
    time: "13.08.2022",
  },
  {
    id: 24,
    img: "../img/blog-item/blog-item-3.png",
    title: "Xayotda shunday vaziyatlar bo‘ladiki, kimdan yordam so‘ramang...",
    dec: "Yaqinda bir psixologning suhbatini eshitib qoldim. U aytishicha o‘sha davrda hech qanday moliyaviy muhim qarorlar qabul qilish kerak emas ekan…",
    time: "13.08.2022",
  },
  {
    id:25,
    img: "../img/blog-item/blog-item-1.png",
    title: "Xayotda shunday vaziyatlar bo‘ladiki, kimdan yordam so‘ramang...",
    dec: "Yaqinda bir psixologning suhbatini eshitib qoldim. U aytishicha o‘sha davrda hech qanday moliyaviy muhim qarorlar qabul qilish kerak emas ekan…",
    time: "13.08.2022",
  },
  {
    id: 26,
    img: "../img/blog-item/blog-item-3.png",
    title: "Xayotda shunday vaziyatlar bo‘ladiki, kimdan yordam so‘ramang...",
    dec: "Yaqinda bir psixologning suhbatini eshitib qoldim. U aytishicha o‘sha davrda hech qanday moliyaviy muhim qarorlar qabul qilish kerak emas ekan…",
    time: "13.08.2022",
  },
  {
    id: 27,
    img: "../img/blog-item/blog-md-item-1.png",
    title: "Xayotda shunday vaziyatlar bo‘ladiki, kimdan yordam so‘ramang...",
    dec: "Yaqinda bir psixologning suhbatini eshitib qoldim. U aytishicha o‘sha davrda hech qanday moliyaviy muhim qarorlar qabul qilish kerak emas ekan…",
    time: "13.08.2022",
  },
  {
    id: 28,
    img: "../img/blog-item/blog-md-item-2.png",
    title: "Xayotda shunday vaziyatlar bo‘ladiki, kimdan yordam so‘ramang...",
    dec: "Yaqinda bir psixologning suhbatini eshitib qoldim. U aytishicha o‘sha davrda hech qanday moliyaviy muhim qarorlar qabul qilish kerak emas ekan…",
    time: "13.08.2023",
  },
];

export default data